# Q-learning Demo

In this demo we try to solve the following maze navigation problem using reinforcement learning.

<img src ="https://docplayer.net/docs-images/98/136918002/images/60-0.jpg" width=70%>

In [0]:
import numpy as np

## Representing the Environment

We first have to represent the maze in our program. A natural choice for representing a maze in Python is a 2D numpy array. In our case, we use 0's to represent free space and 1's to represent obstacles.   

In [0]:
# states s = position in the maze
# actions a=  movement,  ( a = 0 - left, 1 - right, 2 - up, 3 - down )

# Size of the maze
cols = 4
rows = 3

# Start state
start_s = (2,0)

# Goal state
goal_s = (0,3)

# Maze 
maze = np.zeros((3,4))
# obstacles are 1's free space is 0's
maze[1,1] = 1 

# Check to see if things are as they should be
print(maze)

[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]


### The Reward Function
In our example, the agent receives a reward of +1 for reaching the goal, a reward of -1 for entering the fire, and a reward of 0 elsewhere. 

In [0]:
def reward(curr_state):
  # return r = 0 everywhere in the maze except at the goal and at the pit 
  r = 0
  if(curr_state == (0,3)):
    r = 1
  if(curr_state == (1,3)):
    r = -1

  return r

It may be useful to have a function for printing our current state in the environment.

In [0]:
# print current position of agent (indicated by 2) in the maze
def printState(state,maze):
  m = maze.copy()
  m[state] = 2
  print(m)

### The Transition Function
The transition function decides what the next state of our agent should be if an action is applied at some state. It is also responsible for encoding the rules/dynamics of our environment i.e.:



*   If an agent takes an action in a certain direction, it should transition one step in that direction.
*   If the action being taken is invalid (i.e. leads the agent into a wall or obstacle), the agent should stay in the same state.

We will set up our transition function as follows:
* Check if we are at the goal state
* If we are not at the goal then apply selected action a at the current state s and transition to a new state s_new:
 * Check if state s_new is invalid and reset to state s if it is.
* Calculate reward function at state s_new






In [0]:
def step(s,a): # take_action

  # check if goal is reached
  done = False
  if s == goal_s:
    done = True
    s_new = s

  else: # we are not at the goal so apply current action
    # go left
    if (a == 0): 
      s_new = (s[0],s[1] - 1)
      if(s_new[1] < 0 or maze[s_new] == 1):
        s_new = s

    # go right 
    elif (a == 1): 
      s_new = (s[0],s[1] + 1)
      if(s_new[1] == cols  or maze[s_new] == 1):
        s_new = s

    # go up 
    elif (a == 2): 
      s_new = (s[0]-1,s[1])
      if(s_new[0] < 0  or maze[s_new] == 1):
        s_new = s

    # go down 
    elif (a == 3): 
      s_new = (s[0]+1,s[1])
      if(s_new[0] == rows  or maze[s_new] == 1):
        s_new = s
    # invalid action   
    else:
      raise Exception('Invalid action. The value of a was: {}'.format(a))

  # compute reward for new state
  r = reward(s_new)
  
  printState(s_new,maze)
  return s_new, r, done

### The Q-learning Algorithm
Next we code up the Q-learning algorithm according to the following psuedocode:
![Q-learning psuedocode](https://www.researchgate.net/profile/Kao-Shing_Hwang/publication/220776448/figure/fig1/AS:394068661161984@1470964698231/The-Q-Learning-Algorithm-6.png)

In [0]:
# Define and initialise Q as 3x4x4 (i.e. States X Actions ) numpy array
Q = np.random.rand(3,4,4)
print(Q)

[[[0.00548715 0.17383854 0.6260896  0.04106314]
  [0.08867456 0.33937193 0.41712906 0.62902663]
  [0.20140837 0.58116629 0.83037958 0.46228843]
  [0.73611582 0.72056916 0.89693399 0.97567488]]

 [[0.1849557  0.08423636 0.58207156 0.49345999]
  [0.14432388 0.05540564 0.36259009 0.47509996]
  [0.57980483 0.99174139 0.12348297 0.09784504]
  [0.08717914 0.01597829 0.09436219 0.12139561]]

 [[0.05599916 0.01120088 0.65983685 0.21556464]
  [0.69966912 0.2141484  0.13419533 0.71076839]
  [0.74790679 0.84030674 0.17845931 0.19076653]
  [0.06211904 0.95168906 0.68947139 0.488579  ]]]
0.055999158017607686


In [0]:
num_episodes = 100
num_timesteps = 6
gamma = 0.9
actions = ["left","right","up","down"]
alpha = 1 # learning_rate

for episode in range(num_episodes):
  print("##############################################\nEpisode: ",episode)
  # init s (set to start state)
  s = (np.random.randint(3),np.random.randint(4))
  for t in range(num_timesteps):
    a = np.argmax(Q[s])
    print("Going ",actions[a])
    s_new,r,done = step(s,a) 

    # update Q
    Q[s][a] = Q[s][a] + alpha*(r+gamma*np.max(Q[s_new]) - Q[s][a])
    s = s_new
    if(done):
      break

##############################################
Episode:  0
Going  down
[[0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  down
[[0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  down
[[0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  down
[[0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  up
[[0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  down
[[0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
##############################################
Episode:  1
Going  up
[[0. 0. 0. 0.]
 [2. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  up
[[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  up
[[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  up
[[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  up
[[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  up
[[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
##############################################
Episode:  2
Going  down
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 2. 0. 0.]]
Going  down
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 2. 0. 0.]]
Going  left
[[0. 0. 0. 0.

## Evaluating the trained policy
Run trained policy for one episode:

In [0]:
num_timesteps = 6
s = start_s # start from start state
printState(s,maze)
for t in range(num_timesteps):
  # Take action associated with highest Q-value, recall that Q[s] is a vector of 4 elements
  # argmax returns the index of the action with the highest Q-value
  a = np.argmax(Q[s]) 
  print("Going ",actions[a])
  s_new,r,done = step(s,a) 
  # Update state  
  s = s_new
  if(done):
    break

[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [2. 0. 0. 0.]]
Going  up
[[0. 0. 0. 0.]
 [2. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  up
[[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  right
[[0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  right
[[0. 0. 2. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Going  right
[[0. 0. 0. 2.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
